# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20170903_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
